# config.py
REDDIT_CLIENT_ID = "<REDDIT_CLIENT_ID>"
REDDIT_SECRET = "<REDDIT_SECRET>"
REDDIT_USER_AGENT = "<REDDIT_USER_AGENT>
REDDIT_USERNAME = "<REDDIT_USERNAME>"
REDDIT_PASSWORD = "<REDDIT_PASSWORD>"
OPENAI_API_KEY = "<OPENAI_API_KEY>"
